### ISSUE TITLE
404 for 95% of DLs

### ISSUE THREAD

**Issue by nickheyer** [ScottBot10/calibre_annas_archive#6]
```
Starting job: Downloading Scholomance 8_ The Devil's Academy.z-library.epub 
Job: "Downloading Scholomance 8_ The Devil's Academy.z-library.epub" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 85, in start_work
  File "calibre/gui2/ebook_download.py", line 85, in __call__
  File "calibre/gui2/ebook_download.py", line 101, in _download
  File "calibre/gui2/ebook_download.py", line 68, in download_file
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found
 
Called with args: (<calibre.gui2.ui.Main object at 0x70bb1c13bac0>, None, 'https://z-lib.gs//dl/28575059/d53998', "Scholomance 8_ The Devil's Academy.z-library.epub", '', True, [], <bound method StorePlugin.create_browser of <calibre_plugins.store_annas_archive.annas_archive.AnnasArchiveStore object at 0x70bb1f54c590>>) {'notifications': <queue.Queue object at 0x70bb07f53650>, 'abort': <threading.Event at 0x70bb07f51110: unset>, 'log': <calibre.utils.logging.GUILog object at 0x70bb07f51bd0>} 
```

This is a fresh install. Running in a docker calibre with required ports open. Installed latest release.

**Comment by luisg707** [comment]
Access that url;
https://z-lib.gs//dl/28575059/d53998

it's a 404
